### ISSUE TITLE
error while select zip file

### ISSUE THREAD

**Issue by shemshadmh** [HosseinShams00/AdobeConnectDownloader#1]
the program has many errors when select a zip file to convert to video file.
do you have test this feature?

**Comment by HosseinShams00** [comment]
hi please send for me your error image tnx

در تاریخ چهارشنبه ۱۷ اوت ۲۰۲۲،‏ ۱۸:۲۱ Mohammad Hatef Shemshad <
***@***.***> نوشت:

**Comment by HosseinShams00** [comment]
> the program has many errors when select a zip file to convert to video file.
> do you have test this feature?

hi please send your error .
and don't forget that your compressed file must be the same file that you download from the Adobe Connect server. If you enter the link of your meeting, the zip file will be downloaded for you.

**Comment by HosseinShams00** [comment]
Hello, due to the fact that I did not get an answer from you, I closed this issue. If there is a problem, please create a new issue. Thank you
