### ISSUE TITLE
مشکل در فایل Final Video

### ISSUE THREAD

**Issue by rez7a** [HosseinShams00/AdobeConnectDownloader#10]
سلام وقت به‌خیر،
این فایلی که می‌فرستم نمی‌دونم چرا فایل فاینال ویدیوش صفرکیلوبایت ساخته می‌شه.

**Comment by HosseinShams00** [comment]
سلام ممنون میشم حتما از اخرین نسخه استفاده کنید چون تغییراتی اعمال شده و فایلتون هم بررسی میکنم

**Comment by rez7a** [comment]
هم با نسخه جدید هم قدیمی‌تر این مشکل وجود داره.

**Comment by HosseinShams00** [comment]
سلام شما چند ساعت گذاشتید برنامه کار کردید و متوجه شدید مشکل داره ؟ اصلا برنامه بسته میشه و بعدش چک میکنید که فایل نهایی 0 هست حجمش یا ن اصلا بسته نمیشه و شما بررسی رو انجام میدید؟
@rez7a

**Comment by rez7a** [comment]
این فایل رو هم با نسخه جدید و هم قدیم تست کردم، صفحه چندمرحله‌ای تبدیل فایل هم بسته می‌شه و صفحه اصلی برنامه نشون داده می‌شه، ولی صفر کیلوبایته، یکی دو تا فایل دیگه بعد از اون تست کردم مشکلی نداشت.

**Comment by HosseinShams00** [comment]
سلام بررسی کردم مشکل رو پیدا کردم که مشکل بخاطر نوع کیفیت فایلاتونه که متوجه شدم انگار استادتون از دو نوع مانیتور مختلف استفاده کرده بخاطر همین کمی تفاوت هست و این تفاوت خطا به وجود میاره باید زمانی که سرم خلوت تر شد کداشو کلا باز نویسی کنم اگر ممکنه در حال حاضر از خود ادوب استفاده کنید تا مشکل رو حل کنم ممنون

**Comment by rez7a** [comment]
و یه توصیه هم داشتم، اینکه به‌طور پیش‌فرض اسم فایل مقصد همون اسم فایل مبدأ (zip) باشه.

**Comment by HosseinShams00** [comment]
در حال حاضر اگر شما برنامه رو به روز کرده باشید دیگه نام مقصد رو خودتون باید انتخاب کنید و اگر چیزی نزارید نام پیش فرض داده میشه چه برای فایل های افلاین و چه انلاین یا همون لینک از این به بعد شما باید نام خروجی رو تعیین کنید اینطوری دستتون باز تر هست و هر نامی که به دلخواه شما هست میتونید بزارید
@rez7a

**Comment by rez7a** [comment]
نسخه جدید رو دارم فکر می‌کردم بدون وارد کردن نام submit نمی‌شه.

**Comment by rez7a** [comment]
لطفاً وقت داشتین این فایل هم نگاه کنین، تایم اضافه نداره ولی بااین‌حال روی فیکس آدیو گیر می‌کنه.

**Comment by HosseinShams00** [comment]
> لطفاً وقت داشتین این فایل هم نگاه کنین، تایم اضافه نداره ولی بااین‌حال روی فیکس آدیو گیر می‌کنه. https://s30.picofile.com/file/8470745250/mali13.zip.html

سلام یک لطفی کنید به این ایدی تو تلگرام پیام بدید ممنون
@hpouya00

**Comment by HosseinShams00** [comment]
سلام برنامه به روز رسانی شده و مشکل اعلام شده رو بر طرف کردم .
ممنون میشم از اخرین نسخه استفاده کنید و اگر مشکلی بود اطلاع بدید.
