### ISSUE TITLE
پاک شدن فایل بعد از اتمام کار

### ISSUE THREAD

**Issue by zooze35** [HosseinShams00/AdobeConnectDownloader#12]
سلام حسین جان
فایلی رو میخوام دانلود کنم. لینک رو که میفرستم با اینکه نشست باز هست توی مروگر ولی ارور میده که احتمالا لاگین نکردی...

فایل زیپ رو دانلود کردم و به نرم افزار میدم فرایند تا تهش طی میشه ولی فایل ها پاک میشه و خروجی نمیده

**Comment by zooze35** [comment]
از فرایند هم بخوام برات بگم اکسترکت میکنه فایل زیپ رو و اون فولدر extrated data رو تشکیل میده... ولی بعدش همه چی پاک میشه و حتی لینک هم از خود نرم افزار پاک میشه . یعنی انگار فرایند به درستی اتفاق افتاده. ولی فایلی به عنوان خروجی شکل نگرفته
@HosseinShams00

این نکته رو هم اضافه کنم که سری اول ارور اون فایل not available video رو گرفتم که بعد از اینکه تو فولدر ریختم دیگه اروری نگرفتم.
پ.ن1 : از نسخه آخر برنامه استفاده میکنم.
پ.ن2 : احساس میکنم سری اول برنامه فایل صدا رو تشکیل داد ولی فایل
Not Available Video
رو نداشت توی روت و بعد از اینکه فایل رو ریختم توی روت دیگه فایل اودیو هم تشکیل نمیشه.

**Comment by zooze35** [comment]
با فایل دیگه ای چک کردم. خروجی ویس اوکیه به صورت flv و خروجی فیلم هم not availbe video. ولی نهایتا سینک نشده. فایل پی دی اف هم توش قرار داده نشده...

**Comment by HosseinShams00** [comment]
سلام @zooze35 عزیز
برای مورد اولی که گفتید شما باید زمانی که در سامانه لاگین میکنید کلاستون رو باز کنید یعنی روی لینک مربوطه کلیک کنید تا مرورگر پردازش مربوطه رو انجام بده تا برسه به مرحله ای که قرار هست برنامه ادوب کانکت اصلی باز شه و مرورگر پیام بده ایا برنامه رو باز کنم یا نه که شما باید کنسل کنید و اون لینک رو بدید به برنامه نه لینک های دیگه .
برای موارد دیگه هم فولدر extract data صرفا برنامه اطلاعات مورد نیاز خودش رو از فایل زیپ خارج میکنه و اون تو قرار میده و زمانی که کارش تموم میشه اون هارو پاک میکنه که فضای الکی اشغال نشه و در نهایت دو فایل خروجی با نامی که شما تعیین کردید در مکانی که انتخاب کردید میسازه در نتیجه شما نباید به این فایل ها تا زمانی که برنامه کارش تموم میشه دست بزنید و باید منتظر شید تا خودش پاک کنه 
و همچنین برای نصب برنامه شما باید ابزار های مورد نیازش که گذاشتم رو در محلی که برنامه هست قرار بدید در غیر اینصورت خطا میگیرید و در صورتی که خطایی نگرفتید فرایند تولید ویدیو زمان بر هست و باید صبر کنید تا صفحه ای که باز شده بسته بشه اگر دیدید خیلی طول کشیده و چندین ساعت هست که مشغوله ممکنه عوامل مختلفی دخیل باشه که در اون زمان باید فایل زیپ مربوط به کلاس خودتون رو بفرستید تا بررسی کنم
