### ISSUE TITLE
راه حل های بهبود

### ISSUE THREAD

**Issue by mehran-ezati** [HosseinShams00/AdobeConnectDownloader#13]
سلام خسته نباشید
چندتا مشکل
درصورت امکان فقط ویس و فیلم Share شده مدرس را در نرم افزار قرار دهید چرا که اگر حتی در یک قسمت فایلی وجود نداشته باشه یا نتونه دانلود کنه ارور میده و وقتی ادامه رو میزنیم دیگه جلو نمیره نرم افزار.
اینطوری هم نرم افزار سبک تر میشه و هم راحت خروجی میگیره.
فایل ها به سادگی از طریق خود ادوبی کانکت قابل دانلود هستند و تصویر مدرس هم نیازی نیست حقیقتا.

**Comment by mehran-ezati** [comment]
![Untitled](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/72556901/4d5f8e45-9b29-4fca-af1a-9284abdf222a)
این ارور هم خیلی زیاد میاد علتش چی هست؟

**Comment by HosseinShams00** [comment]
سلام خیلی ممنون از نظرتون 
خروجی برنامه به چند شکل هست که یکی ویس خود کلاس یکی صدا و تصویر هست که این تصویر ممکنه به صورت تصویر صفحه بعلاوه تصویر دوربین استاد ( در صورت موجود بودن ) است و حذف کردن تصویر استاد مشکلی برای من نداره و صرفا خودم گفتم شاید کسی بخواد تصویر استاد هم داشته باشه دیگه راحته چون شاید به کار شما نیاد ولی گاها پیش میاد استاد از طریق دوربینش بخواد نوشته یا مطلبی رو نشون بده که اونوقت ممکنه کاربرد هم داشته باشه برای عزیزان دیگه
ارور دوم هم یک خطای جدید هست که صرفا مربوط میشه به ویدیو هایی که استاد تصویر از خودش داده و میکروفون و دوربینش جدا از هم کار میکنن و در بخشی از برنامه خطا میخوره که این مشکل رو شخص دیگری هم گزارش داده بود ولی فعلا چون به شدت سرم شلوغه نرسیدم اصلاحش کنم که در اولین زمانی که فرصتی داشته باشم اینو اصلاح میکنم و اپدیت برنامه رو میزارم.

**Comment by mehran-ezati** [comment]
سلام ممنون از توضیحاتتون.
خسته نباشید... در هر صورت برنامه الان برای بنده کار کرد و همه لیست ها رو دانلود کرد و تبدیل هم انجام داد.

**Comment by HosseinShams00** [comment]
سلام مشکلی که گفته بودید بر طرف شد ‌و برای کلاس هایی که مدرس تصویر از خودش به اشتراک گذاشته هم یک سوال پرسیده میشه و اگر تایید شود اون ویدیو پردازش میشود در غیر اینصورت میتونید اون رو پردازش نکنید و بدون ویدیو دوربین کار کنید
@mehran-ezati

**Comment by mehran-ezati** [comment]
سلام مهندس خسته نباشی
خیلی ممنون ازت ولی نسخه جدید متاسفانه کار نمیکنه. من با نسخه جدید همچنان کار کردم.
![image](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/72556901/d09809c3-27cc-40a7-93a7-d835bd75a9f3)


و محتوای فایل لاگ هم درست نبود.
File Name : mazad - ضبط شده 17 بهمن
Meeting time : 02:21:47.1910000
Count of audio file : 2
 + cameraVoip_0_5 01:31:11.1960000
 + cameraVoip_0_8 00:48:05.0230000
----------
Count of video file : 2
 + screenshare_1_6 00:17:14.4750000
 + screenshare_2_7 01:58:54.2910000
----------
Count of webcam file : 0
==========

وبکم داخل ادوبی کانکت share شده

یک نکته ای که به ذهنم رسید این بود که برای این نرم افزار یک ui خوب در صورتی که فرصت اجرا دارید البته با یک فلوچارت و ux حرفه ای تر پیاده سازی بشه.  و این کار رو میتونم من انجام بدم.

**Comment by HosseinShams00** [comment]
سلام 
ممنون از اینکه تست گرفتی
برای بر طرف کردن خطا باید فایل رو زحمت بکشی بفرستی مثل بقیه دوستان که دیباگ کنم ببینم مشکل کجاس دقیقا ولی تا جایی دیدم انگار وقتی میاد فایل هارو دانلود کنه اینطوری میشه درسته ؟ 
و اینکه در رابطه با ui خودمم خیلی وقته تو فکرشم ولی متاسفانه کمبود وقت دارم تایم کاریم فشردس نمیرسم به این کار اما اگر شما خودتون میتونید ui رو پیاده سازی کنید تو c# میتونید تو یک برنچ دیگه اگر مقدور هست براتون پیاده سازی کنید و بفرست اگر خوب بود بزارمش ولی در حال حاضر ui فعلا ساده در نظر گرفته شده تا کار عزیزان بر طرف شه ایده زیاد دارم حتی میخواستم یک سری تغییرات اساسی بدم ببرمش رو نسخه موبایلی ولی یک سری جاهاش دستم رو بسته 
در کل بازم ممنون و اگر ممکنه فایل جلستون رو برای دیباگ کردن بفرستید بررسی میکنم.
@mehran-ezati

**Comment by mehran-ezati** [comment]
سلام خواهش میکنم
حتما امروز میفرستم فایل های برنامه رو برای دیباگ.
برای ui لطفا یک آیدی تلگرام برام ارسال کن ممنون.
mehranezati13@gmail.com

**Comment by HosseinShams00** [comment]
سلام همینجا براتون مقدور نیست ارسال کنید ؟

**Comment by HosseinShams00** [comment]
سلام @mehran-ezati 
به این اکانتم پیام بدید تو تلگرام
hshamspouya
