### ISSUE TITLE
please login and try again?

### ISSUE THREAD

**Issue by UCparsa** [HosseinShams00/AdobeConnectDownloader#15]
Your URL is wrong or maybe you're not login , please login and try again
سایتی که من ازش میخوام استفاده کنم لینک آدوب کانتکتی به من میده که بدون نیاز به لاگین در آدوب کانکت وارد کلاس میشم. شاید به خاطر همین ارور میده؟

**Comment by HosseinShams00** [comment]
سلام
شما وقتی روی لینک مربوطه کلیک میکنید طبیعتن مرورگر شمارو به صفحه ای میبره که یک سوال میکنه و اونم اینکه ایا توی برنامه ادوب کانکت باز کنم برنامه رو یا میخواهید داخل مرورگر ببینیدیش و یک دکمه میاد با عنوان کنسل یا باز کردن در ادوب کانکت اونو شما باید کنسل کنید و لینک اونو بدید به برنامه

**Comment by HosseinShams00** [comment]
سلام با توجه به اینکه جوابی دریافت نکردم این issue رو میبندم اگر مشکلی خوردید دوباره این بخش رو باز کنید و اعلام کنید ممنون
@UCparsa

**Comment by UCparsa** [comment]
سلام ممنون از وقتی که میذاری
همچنان همین ارور رو دریافت میکنم با اینکه لینکی که شما خودت گفتی رو وارد میکنم.
کلا سایت عجیب غریبیه ، برای ورود باید اول وارد یک لینک تست بشم و بعد روی لینک جلسه‌ای که میخوام کلیک کنم تا وارد بشم وگرنه ادوب کانکت ازم یوزرنیم و پسورد میخواد

**Comment by HosseinShams00** [comment]
سلام @UCparsa 
به این اکانتم پیام بدید تو تلگرام
hshamspouya

**Comment by danialshakib20-cpu** [comment]
درود و وفت بخیر ،من بهتون داخل تلگرام پیام دادم ، لطفا امکانش هست راهنماییم کنید ...

**Comment by HosseinShams00** [comment]
@danialshakib20-cpu 
سلام در حال حاضر دسترسی به تلگرام محدوده برام خواهشا یک issue جدید ایجاد کنید مشکلتون رو به همراه لینک کلاس و عکس خطا قرار بدید تشکر
