### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by itsoli91** [HosseinShams00/AdobeConnectDownloader#16]
Hi,
I have downloaded the meeting zip file, while pressing Process Queue I am receiving below error.

![image](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/10760874/66f1a78d-2d26-47ca-8a63-d6a53aa1e311)

![image](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/10760874/cd4ea554-02d9-4789-8b87-30cfaf939e78)

**Comment by HosseinShams00** [comment]
hi please download adobe connect tools and extract in adobe downloader folder

**Comment by itsoli91** [comment]
What is adobe connect tools? do you have any link to it ?

**Comment by HosseinShams00** [comment]
in release addres you can download it

https://github.com/HosseinShams00/AdobeConnectDownloader/releases/tag/v1.4.0
