### ISSUE TITLE
عدم امکان دانلود

### ISSUE THREAD

**Issue by sina-saharkhiz** [HosseinShams00/AdobeConnectDownloader#18]
سلام وقتتون بخیر یه موردی لینک کلاس های ما کلا متفاوته این مورد قابل ساپورت نیست؟
http://website-domain/pblgcqvdg5qc/?OWASP_CSRFTOKEN=c3266e748311e0421b92688a6a0475cb8062761217b34b75d01f58c6f1775dec&proto=true

**Comment by HosseinShams00** [comment]
سلام 
متاسفانه من خودم هم وقتی از این لینک اومدم وارد کلاس شما بشم کلا خطا خوردم و مشکل از url شما هست من website-domain رو تا حالا ندیدم و برنامه وقتی میخواد اطلاعات بگیره از لینک شما به خطا میخوره شما لینکی که به برنامه میدید در گام اول باید خودتون بتونید وارد شید و کلاس رو ببینید بعدا برنامه هم میتونه اطلاعات بگیره و در ضمن در زمانی که برنامه مشغول هست شما نباید از سامانه لاگ اوت کرده باشید.
همچنین تا جایی اطلاع دارم این سمت شما یک سری تنظیمات خاص صورت گرفته احتمالا که ادرس رو تغییر داده
