### ISSUE TITLE
عدم نصب موفق

### ISSUE THREAD

**Issue by alirezarahimi1393** [HosseinShams00/AdobeConnectDownloader#19]
سلام وقتتون بخیر

درهنگام نصب با مشکل عدم امکان نصب به دلایل امنیتی مواجه شدم 

پیشنهادی دارین؟
![image](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/75953510/8985e726-a985-47ac-9546-be87a7dccc87)

**Comment by HosseinShams00** [comment]
با سلام
اگر از همین گیت هاب دانلود کردید مشکلی نداره شما میتونید از طریق گزینه More Info برنامه رو اجرا کنید و مشکلی بر نمیخورید.
