### ISSUE TITLE
هماهنگ نبودن صدا و تصویر

### ISSUE THREAD

**Issue by rez7a** [HosseinShams00/AdobeConnectDownloader#2]
سلام، خیلی برنامه خوب و کاربردی‌ایه و کار باهاش هم آسونه، ولی متاسفانه صدا و تصویر ویدیوی خروجی هماهنگ نیست.

**Comment by HosseinShams00** [comment]
سلام ممنون از گزارشتون برای بررسی صدا و تصویر نیازمند این هستم که به لینک کلاستون یا فایل ها دسترس داشته باشم و اینکه چند ثانیه اختلاف داره ؟ تا جایی حضور ذهن دارم یک مشکلی که بود و متاسفانه به دلیل مشکلاتی که دارم نتونستم بررسیش کنم این بود که فیلم ها و صداها از اونجایی که جدا هستند معمولا باید با استفاده از فایل توضیحاتش تایم اتصال و... این ها محاسبه بشود و اونجا زمان فیلم و صداها در سطح میلی ثانیه تنظیم شده است که باعث اختلال ابن صدا و تصویر میشه باز هم اگر مقدور هست برام بفرستید مشخصات تا در اسرع وقت پیگیری کنم ممنون از توجهتون

**Comment by rez7a** [comment]
دقیقاً، فایل زیپ رو از طریق ایمیل بفرستم؟ اگر بله ایمیلتون رو بگید تا بفرستم.

> سلام ممنون از گزارشتون برای بررسی صدا و تصویر نیازمند این هستم که به لینک کلاستون یا فایل ها دسترس داشته باشم و اینکه چند ثانیه اختلاف داره ؟ تا جایی حضور ذهن دارم یک مشکلی که بود و متاسفانه به دلیل مشکلاتی که دارم نتونستم بررسیش کنم این بود که فیلم ها و صداها از اونجایی که جدا هستند معمولا باید با استفاده از فایل توضیحاتش تایم اتصال و... این ها محاسبه بشود و اونجا زمان فیلم و صداها در سطح میلی ثانیه تنظیم شده است که باعث اختلال ابن صدا و تصویر میشه باز هم اگر مقدور هست برام بفرستید مشخصات تا در اسرع وقت پیگیری کنم ممنون از توجهتون

**Comment by rez7a** [comment]
این فایل زیپ هستش، برای مثال در دقیقه 1:41:41 صدا تقریباً در موقعیت 1:55:09 هستش، یعنی صدا تقریباً 14 دقیقه اختلاف داره. البته اختلاف به مرور در ویدیو به‌وجود میاد اوایل ویدیو تاخیری وجود نداره.
ریپو زیر هم هست که یه پلیره که فایل ایندکس استریم رو پخش میکنه و با این پلیراً عدم هماهنگی خیلی کمه
https://github.com/SMR76/adobe-connect-offline-player

**Comment by HosseinShams00** [comment]
ممنون حتما در اسرع وقت بررسیش میکنم

**Comment by HosseinShams00** [comment]
@rez7a 
سلام لینک فایلی که گذاشتید متاسفانه رمز عبور میخواد ممنون میشم رمز عبور رو بفرستید

**Comment by rez7a** [comment]
> بفرستید

سلام وقت به‌خیر
رمزش رو برداشتم

**Comment by HosseinShams00** [comment]
ممنون

**Comment by rez7a** [comment]
> ممنون

سپاس از شما بابت پیگیری.

**Comment by HosseinShams00** [comment]
@rez7a 
سلام ممنون میشم تست انجام بدید ببینید بهتر شده یا خیر و یک نکته ای که باید توجه داشته باشید این هست که حتما دقت کنید که کلاس اصلی هم گاها ممکنه از طرف استاد لگ و اختلاف صدا و تصویر وجود داشته باشد
ورژن جدید رو دانلود کنید ممنون
فکر کنم مشکل صداش حل شده الان فقط مشکل تصویر داره باز مطمان نیستم

**Comment by rez7a** [comment]
سلام، خطای زیر رو دریافت می‌کنم و با وجود زدن continue اما عملیات به پایان نمی‌رسه.
نت فریم‌ورک 5 هم نصبه با نسخه قبلی چنین مشکلی نداشتم
![adobe downloader err](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/137928615/cf298609-89ed-409f-ac5a-b6a63ea57e96)

**Comment by HosseinShams00** [comment]
سلام اون فایل عکس رو پیدا نمیکنه 
توی محلی ک فایلا هستن یک عکس وجود داره ممنون میشم اسمشو ب چیزی ک میزارم تغییر بدید من اونو درست میکنم حتما 

Not Available Video.png

**Comment by rez7a** [comment]
اختلاف کمتر شده ولی هنوز حدود 2 دقیقه‌ای اختلاف تصویر و صدا هست در پارتهای پایانی ویدیو.

**Comment by HosseinShams00** [comment]
ممنون در حال بررسی هستم

**Comment by rez7a** [comment]
مثلا توی همین فایلی که براتون فرستادم دقیقه 2:39:36 صدا در موقعیت 2:41:18 هست (به‌صورت تقریبی). یعنی صدا با حدود 2 دقیقه تاخیر پخش می‌شه.

**Comment by HosseinShams00** [comment]
در اصل تا جایی متوجه شدم صدا درست داره تبدیل میشه مشکل اصلی توی تصویر هست تصویر نسبت ب صدا دچار اختلاف هست

**Comment by HosseinShams00** [comment]
@rez7a 
سلام بررسی کردم مشکلش رو پیدا کردم کمی تخصصی بود واقعا ولی خب ممنون میشم تست کنید اگر مشکلی بود بهم بگید من تست کردم باگ های قدیم رو نداشت باز اگر تداخل دیدید بهم بگید 
فقط یک نکته ای رو توجه داشته باشید که گاها پیش میاد فیلم اصلی کلاس رو هم نگاه میکنید اختلاف صدا و تصویر هست ملاک بررسیتون کلاس اصلی و فیلم باشه اگر شبیه هم بودن که اوکیه اگر ن اختلاف جزئی در حد یکی دو ثانیه بود واقعا دیگه کاریش نمیشه کرد

اما فکر کنم باز اون تایم اخرش باگ داره اولاش کامل درست شد من تست کردم

**Comment by rez7a** [comment]
سلام، فایلی که براتون فرستاده بودم رو تست کردم و خیلی خوب بود، در حد 10 ثانیه اختلاف داشت که قابل اغماضه، البته اون باگ آخر ویدیو که گفتین رو داشت. ولی دو سه تا فایل دیگه رو هم خواستم تست کنم که دیگه تو مرحلۀ Fix Audios گیر کرد.

**Comment by rez7a** [comment]
> سلام، فایلی که براتون فرستاده بودم رو تست کردم و خیلی خوب بود، در حد 10 ثانیه اختلاف داشت که قابل اغماضه، البته اون باگ آخر ویدیو که گفتین رو داشت. ولی دو سه تا فایل دیگه رو هم خواستم تست کنم که دیگه تو مرحلۀ Fix Audios گیر کرد.

البته فکر کنم مشکل از سیستم من بود، روی سیستم جدیدم مشکلی از این بابت وجود نداره.

**Comment by HosseinShams00** [comment]
> > سلام، فایلی که براتون فرستاده بودم رو تست کردم و خیلی خوب بود، در حد 10 ثانیه اختلاف داشت که قابل اغماضه، البته اون باگ آخر ویدیو که گفتین رو داشت. ولی دو سه تا فایل دیگه رو هم خواستم تست کنم که دیگه تو مرحلۀ Fix Audios گیر کرد.
> 
> البته فکر کنم مشکل از سیستم من بود، روی سیستم جدیدم مشکلی از این بابت وجود نداره.

سلام راستش خیلی بررسیش کردم خیلی متوجه نشدم مشکل از چی میتونه باشه دوتا احتمال وجود داره براش که فعلا فقط یک راه حل براش دارم ولی نمیخوام برم سمتش چون ساختار برنامم کلا عوض میشه ولی اگر ببینم مشکل همچنان هست کلا بازنویسیش میکنم ببینم مشکل حل میشه یا ن باز اگر مشکلی دیدید ممنون میشم اطلاع بدید که مطمان تر شم مشکل هست و اگر فرصت گیر اوردم حتما بررسیش کنم

**Comment by rez7a** [comment]
> > > سلام، فایلی که براتون فرستاده بودم رو تست کردم و خیلی خوب بود، در حد 10 ثانیه اختلاف داشت که قابل اغماضه، البته اون باگ آخر ویدیو که گفتین رو داشت. ولی دو سه تا فایل دیگه رو هم خواستم تست کنم که دیگه تو مرحلۀ Fix Audios گیر کرد.
> > 
> > 
> > البته فکر کنم مشکل از سیستم من بود، روی سیستم جدیدم مشکلی از این بابت وجود نداره.
> 
> سلام راستش خیلی بررسیش کردم خیلی متوجه نشدم مشکل از چی میتونه باشه دوتا احتمال وجود داره براش که فعلا فقط یک راه حل براش دارم ولی نمیخوام برم سمتش چون ساختار برنامم کلا عوض میشه ولی اگر ببینم مشکل همچنان هست کلا بازنویسیش میکنم ببینم مشکل حل میشه یا ن باز اگر مشکلی دیدید ممنون میشم اطلاع بدید که مطمان تر شم مشکل هست و اگر فرصت گیر اوردم حتما بررسیش کنم

گیر کردن روی مرحلهٔ Fix Audios رو می‌گید؟ روی سیستم جدیدم این مشکل رو نداشتم تا الان، اختلاف صدا و تصویر هم خیلی کمتر شده و چندتا ویدیویی که من تست کردم قابل استفاده بوده، مسلماً اگر امکان کم شدن اختلاف باشه که بهتره ولی تا همینجا هم خیلی زحمت کشیدین بابت این برنامه.

**Comment by HosseinShams00** [comment]
> > > > سلام، فایلی که براتون فرستاده بودم رو تست کردم و خیلی خوب بود، در حد 10 ثانیه اختلاف داشت که قابل اغماضه، البته اون باگ آخر ویدیو که گفتین رو داشت. ولی دو سه تا فایل دیگه رو هم خواستم تست کنم که دیگه تو مرحلۀ Fix Audios گیر کرد.
> > > 
> > > 
> > > البته فکر کنم مشکل از سیستم من بود، روی سیستم جدیدم مشکلی از این بابت وجود نداره.
> > 
> > 
> > سلام راستش خیلی بررسیش کردم خیلی متوجه نشدم مشکل از چی میتونه باشه دوتا احتمال وجود داره براش که فعلا فقط یک راه حل براش دارم ولی نمیخوام برم سمتش چون ساختار برنامم کلا عوض میشه ولی اگر ببینم مشکل همچنان هست کلا بازنویسیش میکنم ببینم مشکل حل میشه یا ن باز اگر مشکلی دیدید ممنون میشم اطلاع بدید که مطمان تر شم مشکل هست و اگر فرصت گیر اوردم حتما بررسیش کنم
> 
> گیر کردن روی مرحلهٔ Fix Audios رو می‌گید؟ روی سیستم جدیدم این مشکل رو نداشتم تا الان، اختلاف صدا و تصویر هم خیلی کمتر شده و چندتا ویدیویی که من تست کردم قابل استفاده بوده، مسلماً اگر امکان کم شدن اختلاف باشه که بهتره ولی تا همینجا هم خیلی زحمت کشیدین بابت این برنامه.

در رابطه با گیر کردن در مرحله Fix audio باید فایل رو بفرستید من بررسی کنم اگر مشکل هست و اختلاف صدا و تصویر ها مرتبط میشه با فایل مربوطه یعنی کلاس با کلاس هم متفاوت میشه طبیعتن هر چی قطع و وصل کردن تصویر در طی تدریس استاد کم باشه این اختلاف ها و خطاها کمتر میشه ولی به هر حال همچنان به صفر نرسیده و فرصت گیر بیارم بررسی میکنم 
و در اخر هم نظر لطفتونه خوشحالم براتون تونسته مفید باشه و استفاده کنید در اینده قصد اضافه کردن چندتا ویژگی مختلف دارم ولی متاصفانه فرصت نمیکنم در کل اگر مشکل بود ممنون میشم اطلاع بدید
