### ISSUE TITLE
ایراد در URL

### ISSUE THREAD

**Issue by hamidtech** [HosseinShams00/AdobeConnectDownloader#20]

**Comment by HosseinShams00** [comment]
سلام @hamidtech 
خواهشا مشکل رو کامل بیان کنید و توضیحات مربوطه رو بنویسید چون متوجه مشکل شما نشدم چون هیچ توضیحاتی ننوشتید.

**Comment by HosseinShams00** [comment]
@hamidtech 
سلام مجدد در صورتی که مشکلتون رفع نشده یک بار دیگه با توضیحات کامل این بخش رو باز کنید و مشکلتون رو کامیت کنید ممنون

**Comment by hamidtech** [comment]
با سلام و احترام

لینکی که در اختیار من قرار گرفته به صورت الگوی زیر است که با الگوی معرفی شده در توضیحات نرم افزار متفاوت است که نرم افزار خطای url اشتباه میدهد:

http://xxxxxxxxxxxx.ir/xxxxxxxxxx/?OWASP_CSRFTOKEN=xxxxxxxxxxxx&proto=true

**Comment by HosseinShams00** [comment]
@hamidtech 
<p dir="RTL"> 
با سلام 
این مورد برای یکی دیگر از دوستان نیز پیش آمده بود و تنها جوابی که برای این موضوع پیدا شد این بود که سامانه ای که از آن استفاده میکنید اجازه دسترسی به فایل ها را بجز مرورگری که لاگین کرده اید به بخش دیگری نمیدهد و شما باید به صورت دستی فایل ها را با آن مرورگری که وارد شده اید دانلود کنید و سپس به صورت افلاین به برنامه معرفی کنید تا عمل تبدیل را انجام دهد.
الگویی که برای دانلود میتونید استفاده کنید به صورت زیر هست :
</p>

http://xxxxxxxxxxxx.ir/yyyyyyyy/output/yyyyyyyy.zip?download=zip

<p dir="RTL">
و در حال حاضر میتونید از این راه استفاده کنید تا در آینده به برنامه امکان شناسایی و دور زدن اینگونه لینک ها هم اضافه شه

</p>
