### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Erfannoob** [HosseinShams00/AdobeConnectDownloader#21]
سلام. این همش میگه your url is wrong maybe your not login please login and try again

**Comment by HosseinShams00** [comment]
سلام @Erfannoob 
لینکی که به برنامه میدید رو اینجا هم بزارید تا بهتر بشه بررسی کرد همچنین فراموش نکنید حتما باید در سامانه مربوطه لاگین باشید و سپس لینک رو بدید به برنامه همچنین فراموش نشه برای بعضی از سامانه ها امکان دانلود بدون پسورد و صرفا با یکبار لاگین کردن رو نمیدن که در حال حاضر راه حل جایگزین این موضوع پیاده سازی نشده و دستی باید اقدام به دانلود فایل کنید و سپس به صورت افلاین ادامه بدید
