### ISSUE TITLE
video quality

### ISSUE THREAD

**Issue by tinkerbell1268** [HosseinShams00/AdobeConnectDownloader#23]
سلام
ممنون بابت نوشتن این برنامه کاربردی
فقط نکته ای که وجود داره اینه که کیفیت ویدئو بعد از merge شدن خیلی پایین میاد .لطفا گزینه ای رو اضافه کنید که کیفیت ویدئو خروجی با فایل FLV  ورودی برابر باشه.
ممنون

**Comment by HosseinShams00** [comment]
سلام @tinkerbell1268 
ممنون از شما
در هنگام تبدیل ویدیو ها خود برنامه جوری تنظیم شده که بالاترین حالت ممکن برای خروجی گرفتن انتخاب میشه و کیفیت همونی هست که در سامانه شما قرارداده شده و این کیفیت بر اساس نسبت تصویر مانیتور استاد شما تنظیم میشه ، در برخی موارد هم پیش میاد به دلیل وجود تصاویر با نسبت تصویر های متفاوت اون تصویری که کوچیکتر هست انتخاب میشه تا نسبت ها بهم نریزه حالا باید ببینید دقیقا کدوم حالت براتون پیش میاد.
برای انتخاب رزولوشن هم خودم بهش فکر کرده بودم ولی خب مشکل جایی هست که هر نسبتی رو نمیشه انتخاب کرد و بابت همین معمولا بالاترین کیفیت ممکن خروجی گرفته میشه و کاربر خودش میتونه تغییر اندازه رو با هر برنامه ای که مد نظر داشت انجام بده.
احتمالا هم توی خروجی فایل zip برنامه هم اگر چک کنید فایل هایی که مربوط به تصویر صفحه هستند رو چک کنید نسبت تصاویر متفاوت دارند.

**Comment by tinkerbell1268** [comment]
این لینک یکی از جلسات کلاسم هست که آموزش unity هست :
https://mega.nz/file/LFxH2Q5a#3VBut2Hi5rRzyttjmqXgiOhgOZcbnhUrFpl-xy0hbMo
ممنون میشم این رو چک کنید ، چون کلاس شامل چندین screenshare و  cameravoip هست ، خروجی درست نمیده  و کیفیت رو هم میتونید ببینید که منظورم چی هست.

**Comment by HosseinShams00** [comment]
سلام @tinkerbell1268 
ممنون از فایلی که فرستادید بله بررسی کردم و مشکل رو متوجه شدم این بخاطر ffmpeg هست که وقتی میاد فایل هارو خروجی بگیره نوع کدک تصویر رو عوض میکنه و متاسفانه ffmpeg از فرمت فلش که مربوط به خروجی فایل های ادوب کانکت هست پشتیبانی نمیکنه و سر همین خرابشون میکنه 
در حال حاضر متاسفانه زمان کافی ندارم بررسی کاملش کنم ولی در صورتی که راه حلی برای این موضوع پیدا کنم برنامه حتما به روز میشه
