### ISSUE TITLE
مرج کردن فایل های ویدویی و صوتی

### ISSUE THREAD

**Issue by ebadola** [HosseinShams00/AdobeConnectDownloader#24]
سلام  خسته نباشید
امکانش هست که شما پوشه یک جلسه دانلود شده  به برنامه بدی (فایل آفلاین را دانلود کردم به صورت zip فایل)
بعد این برنامه خودش فیلم ها و فایل های صوتی را تبدیل کنه به یک فیلم و خروجی به صورت mp4‌ ذخیره کنه

**Comment by ebadola** [comment]
حتی اگر فایل های آفلاین  صفحه اشتراک شده با صدا را با فرمت flv بده هم خوبه

**Comment by HosseinShams00** [comment]
@ebadola 
سلام 
اگر فایل زیپ بدون هیچ تغییری از سامانه مربوطه دانلود شده باشه و فایل های داخلش تغییری نکرده باشه بله امکانش داخل برنامه گذاشته شده همونجایی که شما میایید و لینک خودتون رو میدید به برنامه بجای لینک میتونید فایل خودتون رو از کامپیوتر تون انتخاب کنید و خروجی مورد نظر رو دریافت کنید
