### ISSUE TITLE
کلاس لایو

### ISSUE THREAD

**Issue by daalvand** [HosseinShams00/AdobeConnectDownloader#3]
سلام روزتون به خیر 
راهی هم هست که بشه از کلاس لایو هم فایلاها رو دانلود کرد؟
میدونم با مرورگر میشه خواستم ببینم راهی شبیه همین کدی که شما گذاشتین هست؟

**Comment by HosseinShams00** [comment]
سلام 
با عرض پوزش منظورتون رو متوجه نشدم دقیقا چه چیزی رو میخواهید دانلود کنید ؟
منظورتون همین فایل زیپ هست که محتویات صوت و تصویر توش هست ؟ 
یا منظورتون فایل های پی دی اف هست ؟

**Comment by daalvand** [comment]
نه کلاسی که من میرم رکورد نمیشه 
حالا اگه با مرورگر بری میتونی توی  html لینکای دانلود رو ببینی اگه pdf اشتراک گذاری شده یا هرچیزی 
اگه extenstion idm هم باشه که خودش متوجه میشه و popup میاد و میتونی فایلا رو دانلود کنی 
حالا دنبال یه راه میگردیم که لینک کلاس در حال پخش رو بهش بدی همون لحظه خودش مث ایونت لیسنتر یا اسکچول طور چک کنه فایلی آپلود شد دانلود کنه 
یه چنین چیزی 
فک کنم بتونم با یه چیزی مث puppeteer بنویسم اوکیش کنم ولی دنبال یه راه ساده ترم
@HosseinShams00

**Comment by HosseinShams00** [comment]
متاسفانه نمونه ای از این کلاس هارو در دسترس نداشتم که بررسی کنم باید کامل ببینم و بررسی کنم
