### ISSUE TITLE
Download Assets

### ISSUE THREAD

**Issue by mohamadhashemi8080** [HosseinShams00/AdobeConnectDownloader#4]
سلام ببخشید لینکی ک برای assets ها گذاشتین برای برنامه فیلتره
من فیلتر شکن روشن کردم تا از این مرحله رد شد
اخر سر هم سه دقیقه فایل اکسترکت شده بیشتر از فایل اصلی شد(صوت خالی رو اکسترکت کردم)

**Comment by HosseinShams00** [comment]
سلام
چیزی از جانب برنامه فیلتر نیست اگر هم باشه مربوط میشه به سرور های کلاس شما 
و همچنین شما دستی نباید چیزی رو اکسترکت کنید خود برنامه کارهای مربوطه رو انجام میده و مدت زمانش هم با توجه به نوع مشخصات کامپیوتر شما مختلف هست و ممکنه برای یک کلاسی رو در ۲ دقیقه در یک سیستم انجام بده و در کامپیوتری دیگر در ۲۰ دقیقه انجام شه
و در رابطه با اون مطلبی که گفتید مدت زمان سه دقیقه بیشتر از کلاس اصلیه رو متوجه نشدم یعنی خروجی برنامه نسبت به کلاس واقعی شما ۳ دقیقه بیشتر هست ؟

**Comment by mohamadhashemi8080** [comment]
نگاه کنین من لینک کلاس رو به برنامه دادم، بعد اکثر اوقات روی دانلود است قرمز میشه، وقتی هم که سبز میشه و ادامه رو میره هیچ فایل تصویری به من خروجی نمیده(اون گزینه های پایین سبز نمیشن اصلا و یدفه برمیگرده صفحه اول برنامه رو نشون میده) و یه فایل صوتی خروجی میده که اصلا مطابق صدای جلسه نیست(استاد از دانشجو ها زیاد سوال پرسید و اونا هم صوتی جواب میدادن).کلاس من رکوردش بعضی جاها متوقف شد و بعد مجدد شروع شد،بعضی جاها هم استاد از کلاس رفت بیرون و بعضی جاها هم میکروفون و دوربین ش رو خاموش کرده

**Comment by mohamadhashemi8080** [comment]
بله خروجی به من ۳:۰۸:۲۴ میده در صورتی که کلاس ۳:۰۵:۱۱ است

**Comment by HosseinShams00** [comment]
فایل تصویر در صورتی قابل مشاهده است که حتما استاد از صفحه خودش یا مانیتورش تصویر به اشتراک بزاره دقت کنید زمان هایی هست که استاد صرفا یک فایل پی دی اف اپلود میکنه و روی اون تدریس میکنه اون موقعه شما امکان مشاهده تصویر ندارید چون تصویری موجود نیست
در رابطه با باقی موارد هم در حال حاضر امکان بررسی ندارم اما در اسرع وقت لینک کلاس مورد نظر رو ازتون میگیرم و بررسی میکنم حتما 
ممنون که اطلاع دادید

**Comment by HosseinShams00** [comment]
سلام مجدد
اگر مقدر هست فایل زیپی که برنامه دانلود میکنه رو برام اپلود کنید ممنون
@mohamadhashemi8080

**Comment by mohamadhashemi8080** [comment]
چشم، چطور ارسال کنم؟

**Comment by HosseinShams00** [comment]
سلام سرویس های اپلود فایل زیادی هستن مثل گوگل درایو و... از طریق اونا میتونید بفرستید و لینکش رو قرار بدید
