### ISSUE TITLE
ارور در دانلود

### ISSUE THREAD

**Issue by MegaYagi** [HosseinShams00/AdobeConnectDownloader#5]
با سلام و خسته نباشید. 
من سعی کردم کلاس رکورد شده خودمو دان کنم با این کلاینت ولی خب بهم ارور زیر رو میده:

![image](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/72338441/4d8f51a3-2efe-4871-8a07-e87fad444b3a)

با اینکه من لوگین هم کردم تو سایت مربوطه.
میخواستم بدونم میشه یه جوری فایل temp ای که خودم دانلود کردم از نت رو یه جوری به برنامه بدم تا برام کانورتش به یه ویدیو قابل استفاده بکنه؟

یا روش دیگه ای اصن که بتونه محتوارو از سرور دانشگاه بگیره و کارشو ادامه بده؟

**Comment by HosseinShams00** [comment]
سلام این ارور نشون میده لینکی که میدید به برنامه صحیح نیست اول وارد سامانه بشید بعد بزنید فیلم ظبط شده رو براتون باز کنه توی اون صفحه ای که میخواد برنامه ادوب کانکت رو باز کنه بجای باز کردن با اون برنامه همون لینک رو بدید به برنامه تا براتون دانلود کنه .
در رابطه با سوال های دیگه شما هم باید بگم اگر شما فایل زیپی که مربوط به فایل شما هست رو بدید به برنامه به صورت افلاین میتونه عمل تبدیل رو انجام بده و روش های دانلود هم توی برنامه اعمال شده شما اگر به درستی لینک رو بدید به برنامه میتونه فایل رو براتون دانلود کنه که توی پوشه ای که انتخاب میکنید قرار میده .

**Comment by MegaYagi** [comment]
منم دقیقا همونجوری که خودتون اینجا ذکر کردید تست کردم چندبار ولی نمیدونم چرا نمیزاره.

برنامه هم درست این دفعه چک کردم و دیدم که فایل زیپ رو پشتیبانی میکنه و من حواسم نبود. شرمنده.
از طریق زیپ استفاده کردم و به درستی انجامش داد.
فقط آیا دلیلی داره تو download asset تکست قرمز هست؟
و سوال آخر اینه که آیا میشه کیفیت اکسپورت رو یه ذره برای ویدیو بهتر کرد؟ اگه تنظیماتی داشته باشه.

ببخشید که کلی سوال پرسیدم.

**Comment by HosseinShams00** [comment]
خواهش میکنم هر چی سوال دارید راحت بپرسید
گزینه ای که گفتید زمانی سبز میشه که بتونه یک سرس فایل خاص رو دانلود کنه به عنوان مثال زمانی هست استاد میاد یک پی دی اف اپلود میکنه و از طریق اون تدریس میکنن این برنامه با روش های خاص خودش اونارو دانلود میکنه و بهتون میده
همچنین برای کیفیت فیلم هم باید بگم که کیفیت فیلم ها بالاتریت خروجی ممکن هست و این بستگی داره به مانیتوری که تصویر از این رکورد شده و تغییری توی کیفیت برنامه اعمال نمیکنه.

**Comment by MegaYagi** [comment]
با تشکر فراوان.
ممنون که وقت گذاشتید و خسته نباشید بابت زحمتی که کشیدید. 3>

**Comment by amntheap** [comment]
دقیقا به همین ارور برمیخورم.
لینک جلسه اینه:
https://connect.iust.ac.ir/p87uc97b6lzd/?ptoto=true&html-view=true&session=breezbreezdscdrhkavch5x9c8
