### ISSUE TITLE
Fix Audios مشکل

### ISSUE THREAD

**Issue by rez7a** [HosseinShams00/AdobeConnectDownloader#7]
سلام، این‌بار روی مرحله Fix Audios گیر کرد‌!

**Comment by HosseinShams00** [comment]
سلام بررسی میشه

**Comment by HosseinShams00** [comment]
سلام مشکل برنامه حل شد ممنون که گفتید اپدیت برنامه قرار داده شده و میتونید برنامه رو دانلود و استفاده کنید
اگر مشکل دیگری دیدید ممنون میشم گزارش بدید.
