### ISSUE TITLE
همچنان Fix Audios!

### ISSUE THREAD

**Issue by rez7a** [HosseinShams00/AdobeConnectDownloader#8]
سلام، همچنان مشکل پابرجاست.

**Comment by HosseinShams00** [comment]
سلام کلاس جدید هست یا همون کلاسه ؟

**Comment by rez7a** [comment]
نه یه کلاس دیگه‌ست.

**Comment by HosseinShams00** [comment]
@rez7a 
سلام ممنون از اطلاعی که دادید من بررسی کردم و متوجه شدم که کلاستون یک مشکلی داره و اونم اینکه نزدیک 13 ساعت هست و استاد به درستی کلاس رو نبسته در نتیجه برنامه مجبور هست بجز یک ساعت و نیم تقریبا کلاس شما باقی زمان رو تصویر سیاه ایجاد کنه و این زمان بر هست طبیعتن و باید خیلی صبر کنید تنها یک راه حل میتونم بدم بهتون که موقتی مشکل شما تو اینطور مسائل حل شه و اونم این هست که فایل زیپ مربوطه رو استخراج کنید و در فایل mainstream.xml به دنبال `__stop__` بگردید که متنی شبیه به متن زیر هست 


```
<Message time="46580270" type="data">
        <Method><![CDATA[playEvent]]></Method>
        <String><![CDATA[__stop__]]></String>
</Message>
```

تو اینجا مقدار زمان که به صورت time="" اومده رو باید مقدار 46580270 رو به عددی مثل 5717300 تبدیل کنید تا تایم کلاس کلا بیاد پایین و پردازش شما زودتر انجام شه و یادتون نره که حتما بعد از ذخیره سازی تغییر حتما فایل مربوطه رو دوباره داخل فایل زیپ بزاری و جایگزین قبلی کنی عددی که گفتم رو تنظیم کنید تقریبا میشه تایم اصلی کلاستون که 1 ساعت و 37 دقیقه هست و این مقدار هم به صورت میلی ثانیه هست
حالا اگر بتونم فایل مربوطه هم براتون قرار میدم

**Comment by rez7a** [comment]
ممنون پس همین کارو می‌کنم، فقط چجوری بفهمم مدت زمان اصلی فایل چقدر هست؟

**Comment by HosseinShams00** [comment]
شما همون فایل ضبط شده برنامه رو با ادوب هم باز کنید حتما 12 ساعت میبینید ولی خب بجز اون اگر دنبال اون متنی که گفتم بگردید و مقدار اون عدد که به میلی ثانیه هست رو به ساعت تبدیل کنید تایم اصلی رو متوجه میشید

**Comment by HosseinShams00** [comment]
[mainstream.zip](https://github.com/HosseinShams00/AdobeConnectDownloader/files/13652328/mainstream.zip)
این هم فایل مربوطه که میتونید جایگزین کنید با فایل خودتون 
@rez7a

**Comment by HosseinShams00** [comment]
در صورتی که مشکل همچنان برقرار بود ممنون میشدم اطلاع بدید و در همینجا کامنت جدید بزارید ممنون
